# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de3ae8e142d28c0c93d53cf6de15f252"
name = "qrcode"
handle = "qrcode-156"
application_url = "https://thats-insights-suggest-figured.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newstoretailwind.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://thats-insights-suggest-figured.trycloudflare.com/auth/callback",
  "https://thats-insights-suggest-figured.trycloudflare.com/auth/shopify/callback",
  "https://thats-insights-suggest-figured.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
